/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        display: ["'Syne'","sans-serif"],
        body:    ["'DM Sans'","sans-serif"],
        mono:    ["'JetBrains Mono'","monospace"],
      },
      colors: {
        crisp: {
          bg:       "#0a0b0d",
          surface:  "#111318",
          card:     "#181b22",
          hover:    "#1e2230",
          border:   "#252836",
          border2:  "#2e3347",
          accent:   "#5b6af5",
          accentDk: "#4a58d4",
          accent2:  "#818cf8",
          teal:     "#22d3c8",
          green:    "#22c55e",
          red:      "#ef4444",
          amber:    "#f59e0b",
          muted:    "#6b7280",
          sub:      "#9ca3af",
          text:     "#e8e9f0",
        },
      },
      boxShadow: {
        "accent-sm": "0 2px 8px rgba(91,106,245,0.2)",
        "accent-md": "0 4px 20px rgba(91,106,245,0.3)",
        "card":      "0 4px 24px rgba(0,0,0,0.4)",
      },
      screens: { xs: "375px" },
      keyframes: {
        slideUp:    { from:{opacity:0,transform:"translateY(14px)"},    to:{opacity:1,transform:"translateY(0)"} },
        slideDown:  { from:{opacity:0,transform:"translateY(-10px)"},   to:{opacity:1,transform:"translateY(0)"} },
        slideLeft:  { from:{opacity:0,transform:"translateX(100%)"},    to:{opacity:1,transform:"translateX(0)"} },
        slideBot:   { from:{opacity:0,transform:"translateY(100%)"},    to:{opacity:1,transform:"translateY(0)"} },
        fadeIn:     { from:{opacity:0},                                 to:{opacity:1} },
        scaleIn:    { from:{opacity:0,transform:"scale(0.92)"},         to:{opacity:1,transform:"scale(1)"} },
        msgIn:      { from:{opacity:0,transform:"translateY(8px) scale(0.97)"}, to:{opacity:1,transform:"translateY(0) scale(1)"} },
        msgInR:     { from:{opacity:0,transform:"translateX(8px) scale(0.97)"}, to:{opacity:1,transform:"translateX(0) scale(1)"} },
        pulse2:     { "0%,100%":{opacity:1}, "50%":{opacity:0.35} },
        bounceDot:  { "0%,80%,100%":{transform:"scale(0)"}, "40%":{transform:"scale(1)"} },
        float:      { "0%,100%":{transform:"translateY(0px)"}, "50%":{transform:"translateY(-6px)"} },
        shimmer:    { from:{backgroundPosition:"-200% 0"}, to:{backgroundPosition:"200% 0"} },
        ringPulse:  { "0%":{transform:"scale(1)",opacity:.8}, "100%":{transform:"scale(2.2)",opacity:0} },
        storyGlow:  { "0%,100%":{boxShadow:"0 0 0 2px #5b6af5"}, "50%":{boxShadow:"0 0 0 3px #818cf8,0 0 20px rgba(91,106,245,0.4)"} },
      },
      animation: {
        slideUp:   "slideUp 0.32s cubic-bezier(0.16,1,0.3,1)",
        slideDown: "slideDown 0.25s cubic-bezier(0.16,1,0.3,1)",
        slideLeft: "slideLeft 0.35s cubic-bezier(0.16,1,0.3,1)",
        slideBot:  "slideBot 0.38s cubic-bezier(0.16,1,0.3,1)",
        fadeIn:    "fadeIn 0.2s ease",
        scaleIn:   "scaleIn 0.2s cubic-bezier(0.16,1,0.3,1)",
        msgIn:     "msgIn 0.28s cubic-bezier(0.16,1,0.3,1)",
        msgInR:    "msgInR 0.28s cubic-bezier(0.16,1,0.3,1)",
        pulse2:    "pulse2 1.8s ease-in-out infinite",
        bounceDot: "bounceDot 1.2s ease-in-out infinite",
        float:     "float 3s ease-in-out infinite",
        shimmer:   "shimmer 2s linear infinite",
        ringPulse: "ringPulse 1.8s ease-out infinite",
        storyGlow: "storyGlow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
